### ISSUE TITLE
Option to change composer directory

### ISSUE THREAD

**Issue by karlhepler** [dantleech/vim-phpnamespace#2]
Hey there - I love this plugin, but I'm not able to use it with my projects because I always set my project root outside of the source folder that contains composer.json

I was hoping if it's not too much trouble, if you would be able to make an update that would allow me to customize the composer.json directory.

**Comment by dantleech** [comment]
Hi, probably not - I am currently working on a better tool and should port this functionality soon, e.g.

https://github.com/dantleech/phpactor/pull/14

its a trivial fix however and I would accept a PR you just need to define `let g:vim-phpnamespace#autoload_path="vendor/autoload"` and use that variable instead of the hard coded value (you can then override it in `.vimrc`). I think. (I am no expert with vimscript).

**Comment by karlhepler** [comment]
Thanks. I took a stab at it but didn't get it working well enough for a pull request.

**Comment by karlhepler** [comment]
I wrote a couple of vimscript functions that actually do exactly what I was wanting. Take a look if you like https://github.com/oldtimeguitarguy/vimrc/blob/master/config/functions.vim

**Comment by dantleech** [comment]
Nice :) Realised it wasn't quite as easy as I suggested (u would have needed to pass the autoloader path to the PHP script).

On 10 January 2017 05:26:39 GMT+00:00, Karl Hepler <notifications@github.com> wrote:
>I wrote a couple of vimscript functions that actually do exactly what I
>was wanting. Take a look if you like
>https://github.com/oldtimeguitarguy/vimrc/blob/master/config/functions.vim
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dantleech/vim-phpnamespace/issues/2#issuecomment-271489829

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
